/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
	const hello = trpc.example.hello.useQuery({ text: 'from tRPC' });
	const ogs = trpc.example.og.useQuery(
		// 'https://www.youtube.com/watch?v=cC6HFd1zcbo'
		'https://kaleidawave.github.io/posts/introducing-ezno/'
	);

	if (ogs.data) {
		console.log('data', ogs.data);
	}

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
				<div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
					{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
				</div>
				<div className="w-[33%]">
					<h2>OG Showcase</h2>
					<h4>{(ogs.data as any)?.ogTitle}</h4>
					<img
						alt={(ogs.data as any)?.ogTitle}
						src={(ogs.data as any)?.ogImage?.url}
					/>
				</div>
				<AuthShowcase />
			</main>
		</>
	);
};

export default Home;

const AuthShowcase: React.FC = () => {
	const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

	const { data: sessionData } = useSession();

	return (
		<div className="flex flex-col items-center justify-center gap-2">
			{sessionData && (
				<p className="text-2xl text-blue-500">
					Logged in as {sessionData?.user?.name}
				</p>
			)}
			{secretMessage && (
				<p className="text-2xl text-blue-500">{secretMessage}</p>
			)}
			<button
				className="px-4 py-2 border border-black text-xl rounded-md bg-violet-50 hover:bg-violet-100 shadow-lg'"
				onClick={sessionData ? () => signOut() : () => signIn()}
			>
				{sessionData ? 'Sign out' : 'Sign in'}
			</button>
		</div>
	);
};
